;;; handlebars-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from handlebars-mode.el

(autoload 'handlebars-mode "handlebars-mode" "\


(fn)" t)
(add-to-list 'auto-mode-alist '("\\.handlebars$" . handlebars-mode))
(add-to-list 'auto-mode-alist '("\\.hbs$" . handlebars-mode))
(register-definition-prefixes "handlebars-mode" '("handlebars-"))

;;; End of scraped data

(provide 'handlebars-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; handlebars-mode-autoloads.el ends here
