;;; gh-md-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gh-md.el

(defalias 'gh-md-render-region #'gh-md-convert-region)
(autoload 'gh-md-convert-region "gh-md" "\
Show a preview the markdown from a region from BEGIN to END.

EXPORT writes a file.

(fn BEGIN END &optional EXPORT)" t)
(autoload 'gh-md-render-buffer "gh-md" "\
Render the markdown content from BUFFER." t)
(autoload 'gh-md-export-region "gh-md" "\
Export to a file the markdown content from region BEGIN to END.

(fn BEGIN END)" t)
(autoload 'gh-md-export-buffer "gh-md" "\
Export to a file the markdown content from BUFFER." t)
(register-definition-prefixes "gh-md" '("gh-md-"))

;;; End of scraped data

(provide 'gh-md-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gh-md-autoloads.el ends here
