;;; tempel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tempel.el

(autoload 'tempel-expand "tempel" "\
Expand exactly matching template name at point.
This completion-at-point-function (Capf) returns only the single
exactly matching template name.  As a consequence the completion
UI (e.g. Corfu) does not present the candidates for selection.
If you want to select from a list of templates, use
`tempel-complete' instead.  If INTERACTIVE is nil the function
acts like a Capf, otherwise like an interactive completion
command.

(fn &optional INTERACTIVE)" t)
(autoload 'tempel-complete "tempel" "\
Complete template name at point and expand.
This completion-at-point-function (Capf) returns a list of all
possible template names, which are then displayed in the
completion UI (e.g. Corfu) for selection.  See also
`tempel-expand'.  If INTERACTIVE is nil the function acts like a
Capf, otherwise like an interactive completion command.

(fn &optional INTERACTIVE)" t)
(autoload 'tempel-insert "tempel" "\
Insert TEMPLATE-OR-NAME.
If called interactively, select a template with `completing-read'.

(fn TEMPLATE-OR-NAME)" t)
(autoload 'tempel-key "tempel" "\
Bind KEY to TEMPLATE-OR-NAME in MAP.

(fn KEY TEMPLATE-OR-NAME &optional MAP)" nil t)
(autoload 'tempel-abbrev-mode "tempel" "\
Install Tempel templates as abbrevs.

This is a minor mode.  If called interactively, toggle the
`Tempel-Abbrev mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `tempel-abbrev-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-tempel-abbrev-mode 'globalized-minor-mode t)
(defvar global-tempel-abbrev-mode nil "\
Non-nil if Global Tempel-Abbrev mode is enabled.
See the `global-tempel-abbrev-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-tempel-abbrev-mode'.")
(custom-autoload 'global-tempel-abbrev-mode "tempel" nil)
(autoload 'global-tempel-abbrev-mode "tempel" "\
Toggle Tempel-Abbrev mode in all buffers.
With prefix ARG, enable Global Tempel-Abbrev mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Tempel-Abbrev mode is enabled in all buffers where `tempel--abbrev-on'
would do it.

See `tempel-abbrev-mode' for more information on Tempel-Abbrev mode.

(fn &optional ARG)" t)
(register-definition-prefixes "tempel" '("tempel-"))

;;; End of scraped data

(provide 'tempel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tempel-autoloads.el ends here
