;;; erc-hl-nicks-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from erc-hl-nicks.el

(autoload 'erc-hl-nicks-force-nick-face "erc-hl-nicks" "\
Force nick highlighting to be a certain color for a nick. Both NICK and COLOR
  should be strings.

(fn NICK COLOR)")
(autoload 'erc-hl-nicks-alias-nick "erc-hl-nicks" "\
Manually handle the really wacked out nickname transformations.

(fn NICK &rest NICK-ALIASES)")
(autoload 'erc-hl-nicks "erc-hl-nicks" "\
Retrieves a list of usernames from the server and highlights them")
(make-obsolete 'erc-hl-nicks '"use the `nicks' module in ERC 5.6+ instead." "30.1")
(when (boundp 'erc-modules) (add-to-list 'erc-modules 'hl-nicks))
(eval-after-load 'erc '(progn (unless (featurep 'erc-hl-nicks) (require 'erc-hl-nicks)) (add-to-list 'erc-modules 'hl-nicks t)))
(register-definition-prefixes "erc-hl-nicks" '("erc-hl-nicks-"))

;;; End of scraped data

(provide 'erc-hl-nicks-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; erc-hl-nicks-autoloads.el ends here
