;;; persp-mode-project-bridge-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from persp-mode-project-bridge.el

(defvar persp-mode-project-bridge-mode nil "\
Non-nil if Persp-Mode-Project-Bridge mode is enabled.
See the `persp-mode-project-bridge-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `persp-mode-project-bridge-mode'.")
(custom-autoload 'persp-mode-project-bridge-mode "persp-mode-project-bridge" nil)
(autoload 'persp-mode-project-bridge-mode "persp-mode-project-bridge" "\
`persp-mode' and `project.el' integration.

Creates perspectives for project.el projects.

This is a global minor mode.  If called interactively, toggle the
`Persp-Mode-Project-Bridge mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='persp-mode-project-bridge-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "persp-mode-project-bridge" '("persp-mode-project-bridge-"))

;;; End of scraped data

(provide 'persp-mode-project-bridge-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; persp-mode-project-bridge-autoloads.el ends here
