;;; tempel-collection-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tempel-collection.el

(autoload 'tempel-collection "tempel-collection" "\
Template loader.")
(with-eval-after-load 'tempel (add-to-list 'tempel-template-sources 'tempel-collection 'append))
(register-definition-prefixes "tempel-collection" '("tempel-collection--"))

;;; End of scraped data

(provide 'tempel-collection-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tempel-collection-autoloads.el ends here
