;;; magit-stats-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-stats.el

(autoload 'magit-stats-in-buffer "magit-stats" "\
HTML report in a new buffer." t)
(autoload 'magit-stats-with-viewer "magit-stats" "\
Open HTML report with OS default viewer." t)
(autoload 'magit-stats-json-buffer "magit-stats" "\
JSON report data in a new buffer." t)
(autoload 'magit-stats "magit-stats" "\
Generate GIT Repository Statistics via BACKEND.

(fn BACKEND)" t)
(register-definition-prefixes "magit-stats" '("magit-stats-backends"))

;;; End of scraped data

(provide 'magit-stats-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-stats-autoloads.el ends here
