;;; sass-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sass-mode.el

(autoload 'sass-mode "sass-mode" "\
Major mode for editing Sass files.

\\{sass-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.sass\\'" . sass-mode))
(register-definition-prefixes "sass-mode" '("sass-"))

;;; End of scraped data

(provide 'sass-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sass-mode-autoloads.el ends here
