;;; ibuffer-project-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ibuffer-project.el

 (autoload 'ibuffer-do-sort-by-project-file-relative "ibuffer-project")
 (autoload 'ibuffer-make-column-project-file-relative "ibuffer-project")
(autoload 'ibuffer-project-generate-filter-groups "ibuffer-project" "\
Create ibuffer filters based on project root of buffers.")
(register-definition-prefixes "ibuffer-project" '("ibuffer-project-" "project-root"))

;;; End of scraped data

(provide 'ibuffer-project-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ibuffer-project-autoloads.el ends here
