;;; org-ros-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-ros.el

(autoload 'org-ros "org-ros" "\
Screenshots an image to an org-file." t)
(register-definition-prefixes "org-ros" '("org-ros-"))

;;; End of scraped data

(provide 'org-ros-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-ros-autoloads.el ends here
