;;; lsp-tailwindcss-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lsp-tailwindcss.el

(autoload 'lsp-tailwindcss-rustywind "lsp-tailwindcss" "\
[Experimental] Sort tailwindcss class name using rustywind.
This is an *experimental* feature, please be careful when use." t)
(autoload 'lsp-tailwindcss-rustywind-before-save "lsp-tailwindcss" "\
[Experimental] Run rustywind when saving buffer.
By add this to `before-save-hook',
it only runs when lsp-tailwindcss can be activated,
see `lsp-tailwindcss--activate-p'.
This is an *experimental* feature, please use it carefully.")
(autoload 'lsp-tailwindcss-installed-server-version "lsp-tailwindcss" "\
[Experimental] Get the installed version of tailwindcss language server." t)
(register-definition-prefixes "lsp-tailwindcss" '("lsp-tailwindcss-"))

;;; End of scraped data

(provide 'lsp-tailwindcss-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-tailwindcss-autoloads.el ends here
