;;; vdirel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vdirel.el

(autoload 'vdirel-switch-repository "vdirel" "\
Change current vdir folder to REPOSITORY.
Let the user choose a repository from `vdirel-repositories` and set
`vdirel-repository` accordingly.

(fn REPOSITORY)" t)
(autoload 'vdirel-vdirsyncer-sync-server "vdirel" "\
Ask vdirsyncer to sync REPOSITORY with the server.
You probably want to call `vdirel-refresh-cache' right after
this.  Currently, REPOSITORY is ignored and \"vdirsyncer sync\" is called
without further argument.

(fn &optional REPOSITORY)" t)
(autoload 'vdirel-helm-select-email "vdirel" "\
Let user choose an email address from (REFRESH'ed) REPOSITORY.

(fn &optional REFRESH REPOSITORY)" t)
(register-definition-prefixes "vdirel" '("vdirel-"))

;;; End of scraped data

(provide 'vdirel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vdirel-autoloads.el ends here
