;;; proced-narrow-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from proced-narrow.el

(defvar proced-narrow-map (let ((map (make-sparse-keymap))) (define-key map (kbd "C-g") 'minibuffer-keyboard-quit) (define-key map (kbd "RET") 'exit-minibuffer) (define-key map (kbd "<return>") 'exit-minibuffer) map) "\
Keymap used while `proced-narrow' is reading the pattern.")
(autoload 'proced-narrow "proced-narrow" "\
Narrow a proced buffer to the processes matching a string.

If the string contains spaces, then each word is matched against
the process name separately.  To succeed, all of them have to
match but the order does not matter.  To bring it back to the
original view, you can call `revert buffer' (usually bound to g)." t)
(register-definition-prefixes "proced-narrow" '("proced-narrow-"))

;;; End of scraped data

(provide 'proced-narrow-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; proced-narrow-autoloads.el ends here
